# Config file for automatic testing at travis-ci.org

language: python

python:
    - "3.6"
    - "3.7"
    - "3.8"

script:
    - pip3 install -r requirements.txt
    - flake8 .
    - python3 -m pytest .