services:
  pigeon:
    build: .
    restart: unless-stopped
    command: python3 -m osf_pigeon
    ports:
      - 2020:2020
    env_file:
      - .docker-compose.env
    stdin_open: true
    volumes:
      - /srv
