name: osf-pigeon

on: [push, pull_request]

jobs:
  test-pigeon:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - run: |
        pip3 install -r dev.txt
        flake8 .
        python3 -m pytest .

