name: test-pigeon

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: pip3 install -r dev.txt
    - name: Run flake8
      run: flake8 .
    - name: Run tests
      run: python3 -m pytest .
